### ISSUE TITLE
Convert HTML to PDF

### ISSUE THREAD

**Issue by joao-binenbojm** [joao-binenbojm/Automated-Assesment#9]
We can automatically generated HTML reports with pytest-html. How can we go from here to PDF reports that can be sent to students for easy access.

**Comment by haticeaydinn** [comment]
Task is completed.

Used library: pdfkit
Useful links for implementation: 
- https://www.geeksforgeeks.org/python-convert-html-pdf/
- https://stackoverflow.com/questions/27673870/cant-create-pdf-using-python-pdfkit-error-no-wkhtmltopdf-executable-found

Only "testing_and_generating_pdf.py" file is required to run. 
It will run pytest command and generate pdf file automatically.
